# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

apiVersion: v1
kind: Pod
metadata:
  name: app-new
spec:
  containers:
    - name: app-new
      image: new-app-image-name-placeholder # this will be replaced by real new app image name