# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'install kubearmor components'
description: 'install kubearmor components'
runs:
  using: composite
  steps:
    # Install kubearmor components   
    - name: Download required dependencies
      run: sudo apt-get install -y socat
      shell: bash
    - name: Install karmor
      run: curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin && karmor install
      shell: bash
    - name: Install Discovery-Engine
      run: kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml
      shell: bash