header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: KubeArmor
    content: |
      SPDX-License-Identifier: Apache-2.0

  paths:
    - "**/*.go"
    - "**/*.sh"
    - "**/Dockerfile"

  paths-ignore:
    - ".github/**/*"

  comment: on-failure

dependency:
  files:
    - go.mod