# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'kubearmor-action'
description: 'kubearmor-action'
inputs:
  old-app-image-name:  # old app docker image name
    description: 'Old app docker image name'
    required: true
  new-app-image-name:  # new app docker image name
    description: 'New app docker image name'
    required: true
  filepath: # file path to store baseline and updated file
    description: 'File path to store baseline and updated file'
    required: flase
    default: '/tmp'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: zhy76/kubearmor-action
        ref: dev
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    # Install kubearmor
    - name: Install kubearmor
      uses: zhy76/kubearmor-action/actions/install-kubearmor@dev
    - name: get pod
      run: kubectl get po -A
      shell: bash
    # Excuting the main logic of kubearmor-action by invoke binary file
    - name: Execute
      run: node ${{ github.action_path }}/invoke-binary.js
      env:
        # pass inputs to env FYI: https://github.com/actions/runner/issues/665
        INPUT_OLD-APP-IMAGE-NAME: ${{ inputs.old-app-image-name }}
        INPUT_NEW-APP-IMAGE-NAME: ${{ inputs.new-app-image-name }}
        INPUT_FILEPATH: ${{ inputs.filepath }}
      shell: bash
    - name: get pod
      run: kubectl get po -A
      shell: bash
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install plantuml
      run: |
        curl -sfLo plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2023.9/plantuml-1.2023.9.jar
      shell: bash
    - name: Visulization
      run: |
        curl -O https://raw.githubusercontent.com/accuknox/tools/main/filter-policy && chmod +x filter-policy
        karmor discover --network -n app > app_sys_policies.yaml
        karmor discover --network -n app -p CiliumNetworkPolicy > app_cilium_policies.yaml
        ./filter-policy -f app-policies.yaml -g app_sys.png
        ./filter-policy -f app_cilium_policies.yaml -g app_cilium.png
      shell: bash
    - name: Upload Image
      uses: actions/upload-artifact@v2
      with:
        name: app_visulization
        path: |
          app_sys.png
          app_cilium.png
