# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'kubearmor-action'
description: 'kubearmor-action'
inputs:
  old-app:  # old app manifests address
    description: 'Old app manifests address'
    required: true
  new-app:  # new app manifests address
    description: 'New app manifests address'
    required: true
  filepath: # file path to store baseline and updated file
    description: 'File path to store baseline and updated file'
    required: false
    default: '/tmp'
outputs:
  visualisation-results-artifact:
    description: The name of the artifact containing the visualisation report
    value: ${{ steps.output-results.outputs.visualisation-artifact }}
  sys-visualisation-image:
    description: The name of the actual file in the artifact, which contains the system visualisation report
    value: ${{ steps.output-results.outputs.sys-visualisation-image }}
  network-visualisation-image:
    description: The name of the actual file in the artifact, which contains the network visualisation report
    value: ${{ steps.output-results.outputs.network-visualisation-image }}
    
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: zhy76/kubearmor-action
        ref: dev
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: "on"
    # # Install kubearmor components
    # - name: Install kubearmor components
    #   uses: zhy76/kubearmor-action/actions/install-kubearmor@dev
    # - name: get pod
    #   run: kubectl get po -A
    #   shell: bash
    # # Diff system and network behaviour reportExcuting the main logic of kubearmor-action by invoke binary file
    # - name: Diff system and network behaviour report
    #   uses: zhy76/kubearmor-action/actions/diff-report@dev
    #   env:
    #     # pass inputs to env FYI: https://github.com/actions/runner/issues/665
    #     INPUT_OLD-APP: ${{ inputs.old-app }}
    #     INPUT_NEW-APP: ${{ inputs.new-app }}
    #     INPUT_FILEPATH: ${{ inputs.filepath }}
    #     INPUT_NEW-APP-URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.head_commit.id }}/${{ inputs.new-app }}
    # System and network visualisation report
    - name: System and network visualisation report
      uses: zhy76/kubearmor-action/actions/visual-report@dev
    - name: Set visualisation outputs
      id: output-results
      run: |
        echo "::set-output name=visualisation-artifact::app_visulisation"
        echo "::set-output name=sys-visualisation-image::app_sys_${{ github.event.head_commit.id }}.png"
        echo "::set-output name=network-visualisation-image::app_network_${{ github.event.head_commit.id }}.png"
      shell: bash
