# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'kubearmor-action'
description: 'kubearmor-action'
inputs:
  old-app-image-name:  # old app docker image name
    description: 'Old app docker image name'
    required: true
  new-app-image-name:  # new app docker image name
    description: 'New app docker image name'
    required: true
  filepath: # file path to store baseline and updated file
    description: 'File path to store baseline and updated file'
    required: flase
    default: '/tmp'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: zhy76/kubearmor-action
        ref: dev
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    # Install kubearmor
    - name: Install kubearmor
      uses: zhy76/kubearmor-action/actions/install-kubearmor@dev
    # # Deploy old app
    # - name: Deploy old app
    #   run: kubectl apply -f ./template/app-old.yaml
    # - name: create baseline file
    #   run: |
    #     sleep 150
    #     kubectl get po -A
    #     karmor summary -p app-old > /${{ inputs.filepath }}/baseline
    #     cat /${{ inputs.filepath }}/baseline
    # # Deploy new app
    # - name: Deploy new app
    #   run: kubectl apply -f ./template/app-new.yaml
    # - name: create updated file
    #   run: |
    #     sleep 150
    #     kubectl get po -A
    #     karmor summary -p app-new > /${{ inputs.filepath }}/updated
    #     cat /${{ inputs.filepath }}/updated
    # Excuting the main logic of kubearmor-action by invoke binary file
    - name: Execute
      run: node ${{ github.action_path }}/invoke-binary.js
      env:
        # pass inputs to env FYI: https://github.com/actions/runner/issues/665
        INPUT_OLD-APP-IMAGE-NAME: ${{ inputs.old-app-image-name }}
        INPUT_NEW-APP-IMAGE-NAME: ${{ inputs.new-app-image-name }}
        INPUT_FILEPATH: ${{ inputs.filepath }}
      shell: 
    - name: get pod
      run: kubectl get po -A
      shell: bash

