# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'check all pods are ready, if not, get reason'
description: 'check all pods are ready, if not, get reason'
runs:
  using: composite
  steps:
    # use k8s client to get pod info
    - name: Wait all pods ready, if not, get reason
      run: go mod download; go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
    - name: Get pod info
      run: kubectl get po -A
      shell: bash