# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of KubeArmor

name: 'system and network visualisation report'
description: 'system and network visualisation report'
runs:
  using: composite
  steps:
    # system and network visualisation report
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install graphviz
      run: |
        sudo apt-get install -y graphviz
      shell: bash
    - name: Visulisation
      run: |
        echo ${PWD} && make build-visual-cli
        # karmor summary -n app > summary.json && cat summary.json
        ./visual system -f ${PWD}/test/testdata/test-summary-data.json -o app_sys_${{ github.event.head_commit.id }}.png
        ./visual network --old ${PWD}/test/testdata/old-summary-data.json --new ${PWD}/test/testdata/new-summary-data.json -o app_network_${{ github.event.head_commit.id }}.png
      shell: bash
    - name: Upload Image
      id: app_visulisation
      uses: actions/upload-artifact@v2
      with:
        name: app_visulisation
        path: |
          app_sys_${{ github.event.head_commit.id }}.png
          app_network_${{ github.event.head_commit.id }}.png
    