on:
  push:
    branches: [main]

jobs: 
  install-armor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download required dependencies
        run: |
          sudo apt-get install -y socat
      - name: Setup a Kubernetes environment
        run: ./.github/workflows/install-k3s.sh
      - name: Test connectivity
        run: kubectl get no
      - name: install karmor
        run: curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin && karmor install
      - name: install Discovery-engine
        run: kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml